# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ef5eb39767cc600f3420b8b175fd6b2f2accf85aadb742e436d79b7799f081bac69d01cfb2f9a558b50758d54e40df9b001361ceef4b251a8cc56dacc689be3

test:
  secret_key_base: 9f882c58f62dd47b2d3740f78337117f6c296421d839c2c0085606229b8acfc4ebea8b9d495515d86dc148a4a5933879978f0a432d1b28b8433d01a4898c5e21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
